version: '3'

services:
  metabase:
    image: metabase/metabase:latest
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: examplepassword
      MB_DB_HOST: db  # This refers to the service name of the PostgreSQL container

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: examplepassword
      POSTGRES_DB: metabase
    volumes:
      - metabase-data:/var/lib/postgresql/data

volumes:
  metabase-data: